In [29]:
import pandas as pd

# Import data from files
Read the coutry name and code translation file

In [30]:
codes_data = pd.read_csv("../../00_SharedInput/countrycodes.csv",
                         usecols=["name","alpha-3"])

Read the projected population from the UN 5 year age grouped poplulation tables 1950-2100 
From this table we use the country and age specific population (PopTotal)

In [31]:
pop_data = pd.read_csv("../data/input/WPP2022_Population1JanuaryByAge5GroupSex_Medium.csv",
                       usecols=["ISO3_code","Time","AgeGrp","PopTotal"],
                       dtype= {"ISO3_code":str,"Time":str,"AgeGrp":str,"PopTotal":float})
# Select only entries for countries, both sexes, and the years 1975, 2022 and 2080 and the age category 0-4.
pop_data = pop_data[(pop_data.ISO3_code.notnull()) & 
                    (pop_data.Time.isin(["1975", "2010","2080"]))& 
                    (pop_data.AgeGrp != "0-4")]
pop_data.loc[pop_data.AgeGrp == "5-9", "AgeGrp"] = "05-09"
pop_data.loc[pop_data.AgeGrp == "100+", "AgeGrp"] = "99+"

###
# Read the projected population for 2080 from the UN Poplulation tables 2022-2100 
###
pop_data_temp = pd.read_csv("../data/input/WPP2022_Population1JanuaryBySingleAgeSex_Medium_2022-2100.csv",
                       usecols=["ISO3_code","Time","AgeGrp","PopTotal"],
                       dtype= {"ISO3_code":str,"Time":str,"AgeGrp":str,"PopTotal":float})


# Select only entries for countries, both sexes, and the years 2022 and 2080 and the age category 0-4.
pop_data_temp = pop_data_temp[(pop_data_temp.ISO3_code.notnull()) & 
                              (pop_data_temp.Time.isin(["2080"]))& 
                              (pop_data_temp.AgeGrp.isin(["0","1","2","3","4"]))]

# Combine age group 1-4
pop_data_temp.loc[pop_data_temp.AgeGrp != "0", "AgeGrp"] = "01-04"
pop_data_temp = pop_data_temp.groupby(['ISO3_code', 'Time',"AgeGrp"]).sum().reset_index()
pop_data = pd.concat([pop_data,pop_data_temp])
pop_data = pop_data.sort_values(by=["ISO3_code","Time","AgeGrp"])

###
# Read the projected population for 1975 and 2010 from the UN Poplulation tables 1950-2021 
###
pop_data_temp = pd.read_csv("../data/input/WPP2024_Population1JanuaryBySingleAgeSex_Medium_1950-2023.csv",
                       usecols=["ISO3_code","Time","AgeGrp","PopTotal"],
                       dtype= {"ISO3_code":str,"Time":str,"AgeGrp":str,"PopTotal":float})


# Select only entries for countries, both sexes, and the years 2010 and 2080 and the age category 0-4.
pop_data_temp = pop_data_temp[(pop_data_temp.ISO3_code.notnull()) & 
                              (pop_data_temp.Time.isin(["1975","2010"]))& 
                              (pop_data_temp.AgeGrp.isin(["0","1","2","3","4"]))]

# Combine age group 1-4
pop_data_temp.loc[pop_data_temp.AgeGrp != "0", "AgeGrp"] = "01-04"
pop_data_temp = pop_data_temp.groupby(['ISO3_code', 'Time',"AgeGrp"]).sum().reset_index()
pop_data = pd.concat([pop_data,pop_data_temp])
pop_data = pop_data.sort_values(by=["ISO3_code","Time","AgeGrp"])

# Set the country and age group as index
pop_data["PopTotal"] = pop_data["PopTotal"]*1000
pop_data.set_index(["ISO3_code","AgeGrp"], inplace=True)
pop_data

                  Time  PopTotal
ISO3_code AgeGrp
ABW       0       1975    1269.0
          01-04   1975    4988.0
          05-09   1975    6565.0
          10-14   1975    7758.0
          15-19   1975    7523.0
...                ...       ...
ZWE       80-84   2080  350778.0
          85-89   2080  144641.0
          90-94   2080   50624.0
          95-99   2080   12352.0
          99+     2080    1344.0

[15580 rows x 2 columns]

Read the baseline fatalities of heat from the GDB data base for 2010-2019
From this table we use the coutry and age specific fatalities due to exposure to extreme heat and cold

In [32]:
blf_data = pd.read_csv("../data/input/IHME-GBD_2019_DATA-4d134360-1.csv",
                        usecols=["location_name","age_name","val"])
# Edit the age categories to match the UN data
blf_data.loc[blf_data["age_name"] == "<1 year", "age_name"] = "0"
blf_data.loc[blf_data["age_name"] == "1-4 years", "age_name"] = "01-04"
blf_data.loc[blf_data["age_name"] == "5-9 years", "age_name"] = "05-09"
blf_data.loc[blf_data["age_name"] == "10-14 years", "age_name"] = "10-14"
blf_data.loc[blf_data["age_name"] == "15-19 years", "age_name"] = "15-19"
blf_data.loc[blf_data["age_name"] == "20-24 years", "age_name"] = "20-24"
blf_data.loc[blf_data["age_name"] == "25-29 years", "age_name"] = "25-29"
blf_data.loc[blf_data["age_name"] == "30-34 years", "age_name"] = "30-34"
blf_data.loc[blf_data["age_name"] == "35-39 years", "age_name"] = "35-39"
blf_data.loc[blf_data["age_name"] == "40-44 years", "age_name"] = "40-44"
blf_data.loc[blf_data["age_name"] == "45-49 years", "age_name"] = "45-49"
blf_data.loc[blf_data["age_name"] == "50-54 years", "age_name"] = "50-54"
blf_data.loc[blf_data["age_name"] == "55-59 years", "age_name"] = "55-59"
blf_data.loc[blf_data["age_name"] == "60-64 years", "age_name"] = "60-64"
blf_data.loc[blf_data["age_name"] == "65-69 years", "age_name"] = "65-69"
blf_data.loc[blf_data["age_name"] == "70-74 years", "age_name"] = "70-74"
blf_data.loc[blf_data["age_name"] == "75-79 years", "age_name"] = "75-79"
blf_data.loc[blf_data["age_name"] == "80-84 years", "age_name"] = "80-84"
blf_data.loc[blf_data["age_name"] == "85-89 years", "age_name"] = "85-89"
blf_data.loc[blf_data["age_name"] == "90-94 years", "age_name"] = "90-94"
blf_data.loc[blf_data["age_name"] == "95+ years", "age_name"] = "95-99"

blf_data = blf_data.groupby(["location_name","age_name"]).sum().reset_index()

# Prepare a dataframe with the same structure as the population table
baseline = pop_data.loc[pop_data["Time"] == "2010", "PopTotal"].to_frame().reset_index()
baseline = baseline.rename(columns={'PopTotal': 'val'})
baseline["val"]= 0.0

# Edit the country nammes to use the ISO3 codes
for loc in blf_data["location_name"].unique():
    if loc in codes_data["name"].values:
        iso = codes_data.loc[codes_data["name"] == loc, "alpha-3"].values[0]
        for age in blf_data["age_name"].unique():
            baseline.loc[(baseline["ISO3_code"] == iso)&(baseline["AgeGrp"] == age),"val"] = blf_data.loc[(blf_data["location_name"] == loc)&(blf_data["age_name"] == age), "val"].values[0]
    else:
        print("Could not match country: ",loc)

baseline.set_index(["ISO3_code","AgeGrp"], inplace=True)

# Set the mortality in the same units as the mortality in the UN life tables
baseline["scaled"] = baseline["val"]/(pop_data.loc[pop_data["Time"] == "2010", "PopTotal"])
baseline = baseline.reset_index()
baseline.set_index(["ISO3_code","AgeGrp"], inplace=True)
baseline

                        val    scaled
ISO3_code AgeGrp
ABW       0        0.000000  0.000000
          01-04    0.000000  0.000000
          05-09    0.000000  0.000000
          10-14    0.000000  0.000000
          15-19    0.000000  0.000000
...                     ...       ...
ZWE       80-84   18.646970  0.000432
          85-89    9.907502  0.000529
          90-94    5.639916  0.000940
          95-99    1.674374  0.001131
          99+      0.000000  0.000000

[5194 rows x 2 columns]

Read the projected mortalities from the UN Abridged life tables 2022-2100 
From this table we use the country and age specific: death rate (mx), average number of years lived (ax)

In [33]:
mor_data = pd.read_csv("../data/input/WPP2022_Life_Table_Abridged_Medium_2022-2100.csv",
                       usecols=["ISO3_code","Time","SexID","AgeGrp","AgeGrpSpan","mx","ax"],
                       dtype= {"ISO3_code":str,"Time":str,"SexID":str,"AgeGrp":str,"AgeGrpSpan":int,"mx":float,"ax":float})
# Select only entries for countries, both sexes, and the year 2080.
mor_data = mor_data[(mor_data.ISO3_code.notnull()) & 
                    (mor_data.SexID.eq("3")) & 
                    (mor_data.Time.isin(["2080"]))]
# Rename columns to fit earlier definitions
mor_data.loc[mor_data.AgeGrp == "1-4", "AgeGrp"] = "01-04"
mor_data.loc[mor_data.AgeGrp == "5-9", "AgeGrp"] = "05-09"
mor_data.loc[mor_data.AgeGrp == "100+", "AgeGrp"] = "99+"
mor_data = mor_data.sort_values(by=["ISO3_code","Time","AgeGrp"])

###
# Read the data for 1975 and 2010 from the UN Life Tables tables 1950-2021 
###
mor_data_temp = pd.read_csv("../data/input/WPP2022_Life_Table_Abridged_Medium_1950-2021.csv",
                       usecols=["ISO3_code","Time","SexID","AgeGrp","AgeGrpSpan","mx","ax"],
                       dtype= {"ISO3_code":str,"Time":str,"SexID":str,"AgeGrp":str,"AgeGrpSpan":int,"mx":float,"ax":float})
# Select only entries for countries, both sexes, and the years 1975 and 2010.
mor_data_temp = mor_data_temp[(mor_data_temp.ISO3_code.notnull()) & 
                              (mor_data_temp.SexID.eq("3")) & 
                              (mor_data_temp.Time.isin(["1975","2010"]))]
# Rename columns to fit earlier definitions
mor_data_temp.loc[mor_data_temp.AgeGrp == "1-4", "AgeGrp"] = "01-04"
mor_data_temp.loc[mor_data_temp.AgeGrp == "5-9", "AgeGrp"] = "05-09"
mor_data_temp.loc[mor_data_temp.AgeGrp == "100+", "AgeGrp"] = "99+"
mor_data_temp = mor_data_temp.sort_values(by=["ISO3_code","Time","AgeGrp"])
# Add the two dataframes together
mor_data = pd.concat([mor_data,mor_data_temp])
mor_data = mor_data.sort_values(by=["ISO3_code","Time","AgeGrp"])


# Set the country and age group as index
mor_data.set_index(["ISO3_code","AgeGrp"], inplace=True)
mor_data

                  Time SexID  AgeGrpSpan        mx        ax
ISO3_code AgeGrp
ABW       0       1975     3           1  0.027298  0.117317
          01-04   1975     3           4  0.001368  1.638501
          05-09   1975     3           5  0.000606  2.196568
          10-14   1975     3           5  0.000517  2.747611
          15-19   1975     3           5  0.001182  2.805596
...                ...   ...         ...       ...       ...
ZWE       80-84   2080     3           5  0.100633  2.488839
          85-89   2080     3           5  0.156489  2.347392
          90-94   2080     3           5  0.231448  2.181014
          95-99   2080     3           5  0.328970  1.968089
          99+     2080     3          -1  0.450836  2.218100

[15576 rows x 5 columns]

Read the extreme heat days by country

In [34]:
# Read the extreme heat days for 2010
ehd_00_1975 = pd.read_csv("../data/input/Heat_days_historical_base1981-2010.txt",
                       delimiter = "\t",
                       usecols=["Country","Heat days 2015-2020"],
                       dtype= {"Country":str,"Heat days 2015-2020":float})

# Read the extreme heat days for 2010
ehd_00_2010 = pd.read_csv("../data/input/Heat_days_2010_update.txt",
                       delimiter = "\t",
                       usecols=["Country","Heat days 2015-2020"],
                       dtype= {"Country":str,"Heat days 2015-2020":float})

# Read the extreme cold days for 2010
ecd_00_2010 = pd.read_csv("../data/input/Cold_days_2015-2020.txt",
                       delimiter = "\t",
                       usecols=["Country","Cold days 2015-2020"],
                       dtype= {"Country":str,"Cold days 2015-2020":float})

# Read the extreme heat days for 2080 under RCP 4.5
ehd_45_2080 = pd.read_csv(
                       "../data/input/Heat_days_2080_RCP45_update.txt",
                       delimiter = "\t",
                       usecols=["Country","Heat days 2015-2020"],
                       dtype= {"Country":str,"Heat days 2015-2020":float})

# Read the extreme heat days for 2080 under RCP 8.5
ehd_85_2080 = pd.read_csv(
                       "../data/input/Heat_days_2080_RCP85_update.txt",
                       delimiter = "\t",
                       usecols=["Country","Heat days 2015-2020"],
                       dtype= {"Country":str,"Heat days 2015-2020":float})


# Make a data frame of the same size as the other data frames
ehd = baseline.reset_index().drop(columns = ["scaled"])
ehd["val"] = 0.0
ehd = ehd.rename(columns={'val': '1975'})
ehd["2010"]= 0.0
ehd["45_2080"]= 0.0
ehd["85_2080"]= 0.0
ehd["cold_scale"]= 0.0


# Rename the countries to the ISO codes to match the UN files
for loc in ehd_00_2010["Country"].unique():
    if loc in codes_data["name"].values:
        iso = codes_data.loc[codes_data["name"] == loc, "alpha-3"].values[0]
        ehd.loc[ehd["ISO3_code"] == iso, "1975"] = ehd_00_1975.loc[ehd_00_1975["Country"] == loc, "Heat days 2015-2020"].values[0]
        ehd.loc[ehd["ISO3_code"] == iso, "2010"] = ehd_00_2010.loc[ehd_00_2010["Country"] == loc, "Heat days 2015-2020"].values[0]
        ehd.loc[ehd["ISO3_code"] == iso, "45_2080"] = ehd_45_2080.loc[ehd_45_2080["Country"] == loc, "Heat days 2015-2020"].values[0]
        ehd.loc[ehd["ISO3_code"] == iso, "85_2080"] = ehd_85_2080.loc[ehd_85_2080["Country"] == loc, "Heat days 2015-2020"].values[0]
        ehd.loc[ehd["ISO3_code"] == iso, "cold_scale"] = (ehd_00_2010.loc[ehd_00_2010["Country"] == loc, "Heat days 2015-2020"].values[0]/(ecd_00_2010.loc[ecd_00_2010["Country"] == loc, "Cold days 2015-2020"].values[0]+ ehd_00_2010.loc[ehd_00_2010["Country"] == loc, "Heat days 2015-2020"].values[0]))
    else:
        print("Could not match country: ",loc)

ehd.set_index(["ISO3_code","AgeGrp"], inplace=True)
ehd

                  1975  2010  45_2080  85_2080  cold_scale
ISO3_code AgeGrp
ABW       0        0.0   0.0      0.0      0.0    0.000000
          01-04    0.0   0.0      0.0      0.0    0.000000
          05-09    0.0   0.0      0.0      0.0    0.000000
          10-14    0.0   0.0      0.0      0.0    0.000000
          15-19    0.0   0.0      0.0      0.0    0.000000
...                ...   ...      ...      ...         ...
ZWE       80-84    7.0  13.0     41.0     63.0    0.619048
          85-89    7.0  13.0     41.0     63.0    0.619048
          90-94    7.0  13.0     41.0     63.0    0.619048
          95-99    7.0  13.0     41.0     63.0    0.619048
          99+      7.0  13.0     41.0     63.0    0.619048

[5194 rows x 5 columns]

In [35]:
baseline["scaled"] = baseline["scaled"]*ehd["cold_scale"]
baseline

                        val    scaled
ISO3_code AgeGrp
ABW       0        0.000000  0.000000
          01-04    0.000000  0.000000
          05-09    0.000000  0.000000
          10-14    0.000000  0.000000
          15-19    0.000000  0.000000
...                     ...       ...
ZWE       80-84   18.646970  0.000268
          85-89    9.907502  0.000328
          90-94    5.639916  0.000582
          95-99    1.674374  0.000700
          99+      0.000000  0.000000

[5194 rows x 2 columns]

# Calculate the excess heat fatalities (ehf)
This is done according to the equation ehf_x = blf/pop_2010 * pop_x * ehd_x; where x is the scenario. We start by calculating these values for the past scenarios.

In [36]:
ehf_00_1975 = (baseline["scaled"]
             * ehd["1975"]
             / ehd["2010"]
              ).to_frame(name="val")
ehf_00_1975

                       val
ISO3_code AgeGrp
ABW       0            NaN
          01-04        NaN
          05-09        NaN
          10-14        NaN
          15-19        NaN
...                    ...
ZWE       80-84   0.000144
          85-89   0.000176
          90-94   0.000313
          95-99   0.000377
          99+     0.000000

[5194 rows x 1 columns]

In [37]:
ehf_00_2010 = (baseline["scaled"]
             * ehd["2010"]
             / ehd["2010"]
              ).to_frame(name="val")
ehf_00_2010

                       val
ISO3_code AgeGrp
ABW       0            NaN
          01-04        NaN
          05-09        NaN
          10-14        NaN
          15-19        NaN
...                    ...
ZWE       80-84   0.000268
          85-89   0.000328
          90-94   0.000582
          95-99   0.000700
          99+     0.000000

[5194 rows x 1 columns]

Repeat the calculation for the projected scenarios

In [38]:
ehf_45_2080 = (baseline["scaled"]
             * ehd["45_2080"]
             / ehd["2010"]
              ).to_frame(name="val")
           
ehf_45_2080

                       val
ISO3_code AgeGrp
ABW       0            NaN
          01-04        NaN
          05-09        NaN
          10-14        NaN
          15-19        NaN
...                    ...
ZWE       80-84   0.000844
          85-89   0.001034
          90-94   0.001834
          95-99   0.002207
          99+     0.000000

[5194 rows x 1 columns]

In [39]:
ehf_85_2080 = (baseline["scaled"]
             * ehd["85_2080"]
             / ehd["2010"]
              ).to_frame(name="val")
           
ehf_85_2080

                       val
ISO3_code AgeGrp
ABW       0            NaN
          01-04        NaN
          05-09        NaN
          10-14        NaN
          15-19        NaN
...                    ...
ZWE       80-84   0.001297
          85-89   0.001588
          90-94   0.002819
          95-99   0.003392
          99+     0.000000

[5194 rows x 1 columns]

Create a blank dataframe for the calculation without the impact of extreme heat days.

In [40]:
ehf_blank = ehf_85_2080.copy()
ehf_blank["val"] = 0

testing = (baseline["scaled"]*ehd["2010"]/ehd["2010"]*(pop_data.loc[pop_data["Time"] == "2010", "PopTotal"])).groupby(["ISO3_code"]).sum().reset_index().rename(columns={0:'Casualties2010'})
testing = pd.concat([testing,(baseline["scaled"]*ehd["45_2080"]/ehd["2010"]*(pop_data.loc[pop_data["Time"] == "2080", "PopTotal"])).groupby(["ISO3_code"]).sum().reset_index().rename(columns={0:'Casualties2080'})["Casualties2080"]], axis=1, join='inner')
testing["Rc"] = testing["Casualties2080"]/testing["Casualties2010"]
testing = pd.concat([testing,ehd["2010"].groupby(["ISO3_code"]).mean().reset_index().rename(columns={0:'2010'})["2010"]], axis=1, join='inner')
testing = pd.concat([testing,ehd["2100"].groupby(["ISO3_code"]).mean().reset_index().rename(columns={0:'2080'})["2080"]], axis=1, join='inner')
testing["Rh"] = testing["2080"]/testing["2010"]

testing = pd.concat([testing,(pop_data.loc[pop_data["Time"] == "2010", "PopTotal"].groupby(["ISO3_code"]).sum().reset_index().rename(columns={'PopTotal':'Pop2010'}))["Pop2010"]], axis=1, join='inner')
testing = pd.concat([testing,pop_data.loc[pop_data["Time"] == "2080", "PopTotal"].groupby(["ISO3_code"]).sum().reset_index().rename(columns={'PopTotal':'Pop2080'})["Pop2080"]], axis=1, join='inner')
testing["Rp"] = testing["Pop2080"]/testing["Pop2010"]

testing = testing.loc[testing['ISO3_code'].isin(['AUT', 'BEL', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 
                                                 'EST', 'FIN', 'FRA', 'DEU', 'GRC', 'HUN', 'IRL', 
                                                 'ITA', 'LVA', 'LTU', 'LUX', 'MLT', 'NLD', 'POL', 
                                                 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'SWE', 'CHE',
                                                 'ISL', 'NOR', 'GBR'])]
testing

# Calculate the life expectancy according to Hauer et al 2021
Here we define the life expectancy calculation:

In [47]:
def le(ehf, data):
    # Add the heat fatalities  to the 
    mor = data["mx"] + ehf["val"]
    
    # Probability of dying
    q = (mor* data["AgeGrpSpan"] / (1+(data["AgeGrpSpan"]-data["ax"])*mor )).to_frame(name="val")
    l = q
    l["val"] = (1 - q["val"])
    l["valminone"]= (l.groupby(["ISO3_code"], as_index=False)["val"].cumprod())
    l["val"] = l.groupby(["ISO3_code"], as_index=False)["valminone"].shift(1)
    l.loc[l.val.isna(), "val"] = 1
    l["valminone"] = l["valminone"]*100000
    l["val"] = l["val"]*100000

    # Person years lived
    pyl = (data["ax"] * l["val"] + (data["AgeGrpSpan"] - data["ax"])*l["valminone"]).to_frame(name="val")

    # Total person years lived
    T = (pyl.iloc[::-1].groupby(["ISO3_code"], as_index=False)["val"].cumsum()).iloc[::-1].to_frame(name="val")
    print(T)
    # Life expectancy
    e = (T["val"] / l["val"]).to_frame(name="val")
    return e

Next we calculate the life expectancy for each scenario

In [48]:
# Calculate the life expectancy for 2022 without excess heat deaths
exp_base = le(ehf_blank,mor_data[mor_data["Time"] == "2010"]).reset_index()
exp_table = exp_base[exp_base["AgeGrp"] == "0"]
exp_table = exp_table.rename(columns={"val":"LifeExpNo_00_2010"})
exp_table = exp_table.drop(columns=["AgeGrp"])

# Calculate the life expectancy for 2010
exp_temp = le(ehf_00_2010,mor_data[mor_data["Time"] == "2010"]).reset_index()
exp_table["LifeExp_00_2010"] = exp_temp[exp_temp["AgeGrp"] == "0"]["val"]
exp_table["LE_00_2010"] = 1- (exp_table["LifeExpNo_00_2010"]-exp_table["LifeExp_00_2010"])/10


# Calculate the life expectancy for 1975 without excess heat deaths
exp_temp = le(ehf_blank,mor_data[mor_data["Time"] == "1975"]).reset_index()
exp_table["LifeExpNo_00_1975"] = exp_temp[exp_temp["AgeGrp"] == "0"]["val"]

# Calculate the life expectancy for 1975
exp_temp = le(ehf_00_1975,mor_data[mor_data["Time"] == "1975"]).reset_index()
exp_table["LifeExp_00_1975"] = exp_temp[exp_temp["AgeGrp"] == "0"]["val"]
exp_table["LE_00_1975"] = 1- (exp_table["LifeExpNo_00_1975"]-exp_table["LifeExp_00_1975"])/10


# Calculate the life expectancy for 4.5 2080 without excess heat deaths
exp_temp = le(ehf_blank,mor_data[mor_data["Time"] == "2080"]).reset_index()
exp_table["LifeExpNo_45_2080"] = exp_temp[exp_temp["AgeGrp"] == "0"]["val"]

# Calculate the life expectancy for 4.5 2080
exp_temp = le(ehf_45_2080,mor_data[mor_data["Time"] == "2080"]).reset_index()
exp_table["LifeExp_45_2080"] = exp_temp[exp_temp["AgeGrp"] == "0"]["val"]
exp_table["LE_45_2080"] = 1- (exp_table["LifeExpNo_45_2080"]-exp_table["LifeExp_45_2080"])/10


# Calculate the life expectancy for 8.5 2080 without excess heat deaths
exp_temp = le(ehf_blank,mor_data[mor_data["Time"] == "2080"]).reset_index()
exp_table["LifeExpNo_85_2080"] = exp_temp[exp_temp["AgeGrp"] == "0"]["val"]

# Calculate the life expectancy for 8.5 2080
exp_temp = le(ehf_85_2080,mor_data[mor_data["Time"] == "2080"]).reset_index()
exp_table["LifeExp_85_2080"] = exp_temp[exp_temp["AgeGrp"] == "0"]["val"]
exp_table["LE_85_2080"] = 1- (exp_table["LifeExpNo_85_2080"]-exp_table["LifeExp_85_2080"])/10

                           val
ISO3_code AgeGrp
ABW       0       7.540387e+06
          01-04   7.441752e+06
          05-09   7.048547e+06
          10-14   6.557877e+06
          15-19   6.067731e+06
...                        ...
ZWE       80-84   7.874622e+04
          85-89   3.288963e+04
          90-94   1.026375e+04
          95-99   2.188442e+03
          99+     2.931249e+02

[5194 rows x 1 columns]
                           val
ISO3_code AgeGrp
ABW       0                NaN
          01-04            NaN
          05-09            NaN
          10-14            NaN
          15-19            NaN
...                        ...
ZWE       80-84   78285.021391
          85-89   32649.697738
          90-94   10167.030145
          95-99    2160.674570
          99+       288.423566

[5194 rows x 1 columns]
                           val
ISO3_code AgeGrp
ABW       0       6.976207e+06
          01-04   6.878559e+06
          05-09   6.490475e+06
          10-14   6.007278e+06
          15-19   5.525284e+06
...                        ...
ZWE       80-84   1.196711e+05
          85-89   4.402865e+04
          90-94   1.159583e+04
          95-99   1.984862e+03
          99+     2.014988e+02

[5194 rows x 1 columns]
                            val
ISO3_code AgeGrp
ABW       0                 NaN
          01-04             NaN
          05-09             NaN
          10-14             NaN
          15-19             NaN
...                         ...
ZWE       80-84   119304.111336
          85-89    43858.860431
          90-94    11537.311600
          95-99     1971.021923
          99+        199.657988

[5194 rows x 1 columns]
                           val
ISO3_code AgeGrp
ABW       0       8.527370e+06
          01-04   8.427617e+06
          05-09   8.028885e+06
          10-14   7.530665e+06
          15-19   7.032585e+06
...                        ...
ZWE       80-84   2.451593e+05
          85-89   1.082451e+05
          90-94   3.572539e+04
          95-99   7.960305e+03
          99+     1.076618e+03

[5194 rows x 1 columns]
                            val
ISO3_code AgeGrp
ABW       0                 NaN
          01-04             NaN
          05-09             NaN
          10-14             NaN
          15-19             NaN
...                         ...
ZWE       80-84   240601.785835
          85-89   105758.927303
          90-94    34674.265473
          95-99     7647.576780
          99+       1023.282658

[5194 rows x 1 columns]
                           val
ISO3_code AgeGrp
ABW       0       8.527370e+06
          01-04   8.427617e+06
          05-09   8.028885e+06
          10-14   7.530665e+06
          15-19   7.032585e+06
...                        ...
ZWE       80-84   2.451593e+05
          85-89   1.082451e+05
          90-94   3.572539e+04
          95-99   7.960305e+03
          99+     1.076618e+03

[5194 rows x 1 columns]
                            val
ISO3_code AgeGrp
ABW       0                 NaN
          01-04             NaN
          05-09             NaN
          10-14             NaN
          15-19             NaN
...                         ...
ZWE       80-84   238193.623707
          85-89   104449.355664
          90-94    34123.147329
          95-99     7484.656177
          99+        995.670779

[5194 rows x 1 columns]

Next we add all of the necessary columns needed for the rest of the PLEES index.

In [52]:
# Add column for the country names
exp_table["country_name"] = exp_table["ISO3_code"]
exp_table["continent"]    = exp_table["ISO3_code"]

# Read the unified country names and codes file
codes_data = pd.read_csv("../../00_SharedInput/countrycodes.csv",
                         usecols=["country_name","country_code","continent"])

for loc in exp_table["ISO3_code"].unique():
    if loc in codes_data["country_code"].values:
        exp_table.loc[exp_table["ISO3_code"] == loc, "continent"] = codes_data.loc[codes_data["country_code"] == loc, "continent"].values[0]
        exp_table.loc[exp_table["ISO3_code"] == loc, "country_name"] = codes_data.loc[codes_data["country_code"] == loc, "country_name"].values[0]
    else:
        print("Could not match country: ",loc)

exp_table = exp_table.rename(columns={"ISO3_code":"country_code"})
exp_table = exp_table.dropna()
exp_table = exp_table[["country_name","country_code","continent",
          "LifeExpNo_00_1975","LifeExp_00_1975","LE_00_1975",
          "LifeExpNo_00_2010","LifeExp_00_2010","LE_00_2010",
          "LifeExpNo_45_2080","LifeExp_45_2080","LE_45_2080",
          "LifeExpNo_85_2080","LifeExp_85_2080","LE_85_2080"]]
exp_table

,country_name,country_code,continent,LifeExpNo_00_1975,LifeExp_00_1975,LE_00_1975,LifeExpNo_00_2010,LifeExp_00_2010,LE_00_2010,LifeExpNo_45_2080,LifeExp_45_2080,LE_45_2080,LifeExpNo_85_2080,LifeExp_85_2080,LE_85_2080
22,Afghanistan,AFG,Asia,40.100329,40.091166,0.999084,60.850774,60.802056,0.995128,74.619626,74.428330,0.980870,74.619626,74.322910,0.970328
44,Angola,AGO,Africa,41.190881,41.177521,0.998664,56.725797,56.638351,0.991255,71.379695,71.016355,0.963666,71.379695,70.911533,0.953184
88,Albania,ALB,Europe,68.327511,68.318009,0.999050,77.935854,77.901628,0.996577,88.531171,88.429612,0.989844,88.531171,88.362864,0.983169
132,United Arab Emirates,ARE,Asia,65.080064,65.059782,0.997972,78.333472,78.163373,0.982990,88.906163,88.076147,0.916998,88.906163,87.791382,0.888522
154,Argentina,ARG,Americas,67.080637,67.074688,0.999405,75.720773,75.705605,0.998483,86.316141,86.273453,0.995731,86.316141,86.250354,0.993421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5084,Kosovo,XKX,Europe,66.134423,66.134423,1.000000,77.629959,77.629959,1.000000,87.497391,87.497391,1.000000,87.497391,87.497391,1.000000
5106,Yemen,YEM,Asia,45.244779,45.240850,0.999607,67.279970,67.242621,0.996265,75.710546,75.563335,0.985279,75.710546,75.520754,0.981021
5128,South Africa,ZAF,Africa,57.511832,57.464424,0.995259,58.898750,58.795756,0.989701,73.727666,73.336074,0.960841,73.727666,73.131338,0.940367
5150,Zambia,ZMB,Africa,54.238652,54.202491,0.996384,56.799087,56.695155,0.989607,71.436702,70.965953,0.952925,71.436702,70.767054,0.933035
5172,Zimbabwe,ZWE,Africa,57.552115,57.529973,0.997786,50.652329,50.624014,0.997169,69.256757,69.070319,0.981356,69.256757,68.970968,0.971421

Save the information a detailed file and abridged file.

In [53]:
exp_table.to_csv("../data/output/LE_detailed.csv", index=False)
exp_table[["country_name","country_code","continent",
          "LE_00_1975","LE_00_2010","LE_45_2080","LE_85_2080"
         ]].to_csv("../data/output/LE.csv", index=False)